/**
 * GPU Throughput Specifications
 *
 * Loaded from gpu_specs.json (generated by the pipeline from dbgpu/TechPowerUp).
 * Used for calculating decode throughput and stream capacity estimates.
 */

import gpuSpecsData from "../../public/data/gpu_specs.json";

export interface GpuThroughputSpec {
  /** VRAM capacity in GB */
  memory_size_gb: number;

  /** FP16 TFLOPS (shader performance from TechPowerUp) */
  fp16_tflops: number;

  /** Memory bandwidth in TB/s */
  memory_bandwidth_tb_s: number;

  /** NVLink bandwidth in GB/s (null for PCIe-only GPUs) */
  nvlink_bandwidth_gb_s: number | null;

  /** FP8 support multiplier (2x for Hopper and newer, 1x for older) */
  fp8_multiplier: number;

  /** Architecture generation (for reference) */
  architecture: string;
}

/**
 * GPU throughput specifications by GPU name.
 *
 * Built from pipeline-generated gpu_specs.json at module load time.
 */
export const GPU_THROUGHPUT_SPECS: Record<string, GpuThroughputSpec> = {};

for (const entry of gpuSpecsData) {
  GPU_THROUGHPUT_SPECS[entry.gpu_name] = {
    memory_size_gb: entry.memory_size_gb,
    fp16_tflops: entry.fp16_tflops,
    memory_bandwidth_tb_s: entry.memory_bandwidth_tb_s,
    nvlink_bandwidth_gb_s: entry.nvlink_bandwidth_gb_s,
    fp8_multiplier: entry.fp8_multiplier,
    architecture: entry.architecture,
  };
}

/**
 * Get GPU throughput spec by name.
 * Returns null if GPU not found in specs.
 */
export function getGpuThroughputSpec(gpuName: string): GpuThroughputSpec | null {
  return GPU_THROUGHPUT_SPECS[gpuName] || null;
}

/**
 * Get GPU VRAM capacity in GB.
 * Returns null if GPU not found in specs.
 */
export function getGpuVram(gpuName: string): number | null {
  const spec = getGpuThroughputSpec(gpuName);
  return spec?.memory_size_gb ?? null;
}

/**
 * Check if GPU supports FP8 compute (Hopper and newer).
 */
export function supportsFp8(gpuName: string): boolean {
  const spec = getGpuThroughputSpec(gpuName);
  return spec?.fp8_multiplier === 2;
}

const FP8_KV_CACHE_ARCHITECTURES = new Set(["Ada Lovelace", "Hopper", "Blackwell"]);

/**
 * Check if GPU supports FP8 KV cache (Ada Lovelace, Hopper, and Blackwell).
 *
 * FP8 KV cache support is broader than FP8 compute — Ada Lovelace GPUs
 * (L4, L40S, RTX 4090, etc.) support FP8 KV cache but not FP8 compute.
 */
export function supportsFp8KvCache(gpuName: string): boolean {
  const spec = getGpuThroughputSpec(gpuName);
  if (!spec) return false;
  return FP8_KV_CACHE_ARCHITECTURES.has(spec.architecture);
}
