/**
 * GPU Throughput Specifications
 *
 * Loaded from gpu_specs.json (generated by the pipeline from dbgpu/TechPowerUp).
 * Used for calculating decode throughput and stream capacity estimates.
 */

import type { InterconnectTier } from "@/types";
import gpuSpecsData from "../../public/data/gpu_specs.json";

export interface GpuThroughputSpec {
  /** VRAM capacity in GB */
  memory_size_gb: number;

  /** FP16 TFLOPS (shader performance from TechPowerUp) */
  fp16_tflops: number;

  /** Memory bandwidth in TB/s */
  memory_bandwidth_tb_s: number;

  /** PCIe link bandwidth in GB/s (unidirectional x16, by PCIe generation) */
  pcie_bandwidth_gb_s: number | null;

  /** NVLink bandwidth in GB/s (null for PCIe-only GPUs) */
  nvlink_bandwidth_gb_s: number | null;

  /**
   * Normalized inter-GPU interconnect tier, derived from the NVLink/NVSwitch
   * form factor. See {@link InterconnectTier}.
   */
  interconnect_tier: InterconnectTier;

  /** Memory technology (e.g. "HBM3e", "GDDR6X"); null if unknown */
  memory_type: string | null;

  /** FP8 support multiplier (2x for Hopper and newer, 1x for older) */
  fp8_multiplier: number;

  /** Architecture generation (for reference) */
  architecture: string;
}

/**
 * Normalize an interconnect tier from a raw spec entry. Prefers an explicit
 * `interconnect_tier`; falls back to the NVLink-bandwidth signal so older data
 * (or a partial pipeline regen) still resolves a sensible tier:
 * `none` when there is no NVLink, else the conservative `nvlink_paired`.
 */
function normalizeInterconnectTier(entry: {
  interconnect_tier?: string | null;
  nvlink_bandwidth_gb_s?: number | null;
}): InterconnectTier {
  const t = entry.interconnect_tier;
  if (t === "none" || t === "nvlink_paired" || t === "nvswitch") return t;
  return entry.nvlink_bandwidth_gb_s == null ? "none" : "nvlink_paired";
}

/**
 * Coerce a raw interconnect value to a canonical {@link InterconnectTier} when
 * it names one exactly — the tier-override case (e.g. the budget custom-config
 * interconnect control). Legacy/descriptive strings ("nvlink", "pcie", provider
 * labels) return null, so callers fall back to the GPU's datasheet tier.
 */
export function asInterconnectTier(value: string | null | undefined): InterconnectTier | null {
  return value === "none" || value === "nvlink_paired" || value === "nvswitch" ? value : null;
}

/**
 * The effective interconnect tier for a deployment: an explicit tier override on
 * the config/offering when present, else the GPU datasheet's tier. Mirrors how
 * {@link calcDeploymentEstimate} resolves the tier, so UI labels match the math.
 */
export function resolveInterconnectTier(interconnect: string | null, gpuName: string): InterconnectTier {
  return asInterconnectTier(interconnect) ?? getGpuThroughputSpec(gpuName)?.interconnect_tier ?? "none";
}

/**
 * GPU throughput specifications by GPU name.
 *
 * Built from pipeline-generated gpu_specs.json at module load time.
 */
export const GPU_THROUGHPUT_SPECS: Record<string, GpuThroughputSpec> = {};
const GPU_THROUGHPUT_SPECS_LOWER: Record<string, GpuThroughputSpec> = {};

for (const entry of gpuSpecsData) {
  const spec: GpuThroughputSpec = {
    memory_size_gb: entry.memory_size_gb,
    fp16_tflops: entry.fp16_tflops,
    memory_bandwidth_tb_s: entry.memory_bandwidth_tb_s,
    pcie_bandwidth_gb_s: entry.pcie_bandwidth_gb_s ?? null,
    nvlink_bandwidth_gb_s: entry.nvlink_bandwidth_gb_s,
    interconnect_tier: normalizeInterconnectTier(entry),
    memory_type: entry.memory_type ?? null,
    fp8_multiplier: entry.fp8_multiplier,
    architecture: entry.architecture,
  };
  GPU_THROUGHPUT_SPECS[entry.gpu_name] = spec;
  GPU_THROUGHPUT_SPECS_LOWER[entry.gpu_name.toLowerCase()] = spec;
}

/**
 * Get GPU throughput spec by name.
 * Returns null if GPU not found in specs.
 */
export function getGpuThroughputSpec(gpuName: string): GpuThroughputSpec | null {
  return GPU_THROUGHPUT_SPECS[gpuName] ?? GPU_THROUGHPUT_SPECS_LOWER[gpuName.toLowerCase()] ?? null;
}

/**
 * Get GPU VRAM capacity in GB.
 * Returns null if GPU not found in specs.
 */
export function getGpuVram(gpuName: string): number | null {
  const spec = getGpuThroughputSpec(gpuName);
  return spec?.memory_size_gb ?? null;
}

/**
 * Check if GPU supports FP8 compute (Hopper and newer).
 */
export function supportsFp8(gpuName: string): boolean {
  const spec = getGpuThroughputSpec(gpuName);
  return spec?.fp8_multiplier === 2;
}

const FP8_KV_CACHE_ARCHITECTURES = new Set(["Ada Lovelace", "Hopper", "Blackwell"]);

/**
 * Check if GPU supports FP8 KV cache (Ada Lovelace, Hopper, and Blackwell).
 *
 * FP8 KV cache support is broader than FP8 compute — Ada Lovelace GPUs
 * (L4, L40S, RTX 4090, etc.) support FP8 KV cache but not FP8 compute.
 */
export function supportsFp8KvCache(gpuName: string): boolean {
  const spec = getGpuThroughputSpec(gpuName);
  if (!spec) return false;
  return FP8_KV_CACHE_ARCHITECTURES.has(spec.architecture);
}
